resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: gitta-jfrog/pipelines-gpu-mnist
      branches:
        include: master
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: SampleApp
      buildNumber: 1          
pipelines:  
  - name: mnist
    configuration:
      runtime:      
        type: image
        image:
          custom:
            name: tensorflow/tensorflow
            tag: latest
            options: "-e HOME=/root" 
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo
          outputResources:
            - name: myBuildInfo             
        execution:
          onExecute:
            - echo $my_env_var
            - if [ -z $app_version ]; then add_pipeline_variables app_version=1.0.0; else app_version=$(bump_semver $app_version minor); fi
            - write_output myBuildInfo "buildNumber=$app_version"
            - add_run_variables run_var="hello"
