resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: my_github
      path: gitta-jfrog/pipelines-gpu-imdb
      branches:
        include: main         
pipelines:  
  - name: imab-train
    configuration:
      runtime:      
        type: image
        image:
          custom:
            name: tensorflow/tensorflow
            tag: latest
            options: "-e HOME=/root" 
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myGitRepo           
        execution:
          onExecute:
            - python imdb.py
